server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://rm-m5es50j9lfj56x323jo.mysql.rds.aliyuncs.com:3306/alpha?allowMulitQueries=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: Tonsan123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl